### ISSUE TITLE
Error when uploading brd file

### ISSUE THREAD

**Issue by Iklon** [marmni/FreeCAD-PCB#6]
When I try to just upload a .brd file, the following error pops up:

no element found: line 1, column 11
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Iklon\AppData\Roaming\FreeCAD\Mod\pcb\PCBbrd.py", line 72, in open
    importBRD(filename, wersjaFormatu[0])
  File "C:\Users\Iklon\AppData\Roaming\FreeCAD\Mod\pcb\PCBbrd.py", line 241, in importBRD
    plytka = plytkaPCB.generate(doc, groupBRD, filename)
  File "C:\Users\Iklon\AppData\Roaming\FreeCAD\Mod\pcb\formats\eagle.py", line 422, in generate
    board = self.getPCB()
  File "C:\Users\Iklon\AppData\Roaming\FreeCAD\Mod\pcb\formats\eagle.py", line 374, in getPCB
    for j in self.getWires(self.libraries[i['library']][i['package']], 20, [i['x'], i['y']]):
<type 'exceptions.KeyError'>: ('rcl" library_urn="urn:adsk.eagle:library:334',)

**Comment by marmni** [comment]
Hi,
try this version - https://github.com/marmni/FreeCAD-PCB/tree/FC_0.18. Old version of freecad-pcb does not support newest eagle (>8.0).
